name: Manual Trigger Workflow

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to run tests in'
        required: true
        default: 'staging'
      scope:
        description: 'Test scope'
        required: false
        default: '@tiger-regression'
      send_to_testrail:
        description: 'Send results to TestRail'
        required: false
        default: 'false'
      testrun_title:
        description: 'Title for the Test Run'
        required: false
        default: 'manual_run'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Install Playwright browsers
        run: npx playwright install

      - name: Set environment variables
        run: |
          echo "ENVIRONMENT=${{ github.event.inputs.environment }}" >> $GITHUB_ENV
          echo "SCOPE=${{ github.event.inputs.scope }}" >> $GITHUB_ENV
          echo "TESTRAIL=${{ github.event.inputs.send_to_testrail }}" >> $GITHUB_ENV
          echo "TITLE=${{ github.event.inputs.testrun_title }}" >> $GITHUB_ENV

      - name: Run Playwright tests
        run: npx playwright test
        env:
          BASE_URL: ${{ env.baseUrl }}
          